// Fixture pages: one per way a font can reach a page.
// Every case uses its own fonts (fNN), registered on the page as "Vec NN" (internal name "Int NN").
// expect: font ids the bookmarklet should deliver as files. hard: needs page hooks to be fully solvable.
import fs from "node:fs";
import path from "node:path";

const FONTS = path.join(path.dirname(new URL(import.meta.url).pathname), "fonts");
export const fontBytes = (id, fmt = "woff2") => fs.readFileSync(path.join(FONTS, `f${String(id).padStart(2, "0")}.${fmt}`));
const b64 = (id, fmt) => fontBytes(id, fmt).toString("base64");
const p2 = id => String(id).padStart(2, "0");
const fam = id => `Vec ${p2(id)}`;
const ff = (id, url, extra = "") => `@font-face{font-family:"${fam(id)}";src:url("${url}");${extra}}`;
const use = (...ids) => ids.map(id => `<p style="font-family:'${fam(id)}',monospace">${fam(id)} — The quick brown fox</p>`).join("\n");
const page = (body, head = "") => `<!doctype html><html><head><meta charset="utf-8">${head}</head><body>${body}</body></html>`;
const js = body => ({ type: "text/javascript", body });
const css = body => ({ type: "text/css", body });
const json = body => ({ type: "application/json", body: JSON.stringify(body) });
// Inline script that registers a JS FontFace from a source expression and renders it
const jsFace = (id, srcExpr, load = true) => `(async()=>{const f=new FontFace(${JSON.stringify(fam(id))},${srcExpr});document.fonts.add(f);${load ? "await f.load();" : ""}})();`;

export function cases({ A, B }) {
  const F = (id, fmt = "woff2") => `/fonts/f${p2(id)}.${fmt}`;
  return [
    { id: "css-link", desc: "<link> stylesheet, same origin", expect: [1],
      files: { "a.css": css(ff(1, F(1))) },
      html: page(use(1), `<link rel=stylesheet href="a.css">`) },
    { id: "css-link-xorigin", desc: "cross-origin stylesheet without CORS (unreadable CSSOM), relative font URL", expect: [2],
      html: page(use(2), `<link rel=stylesheet href="${B}/nocors/case-assets/css-link-xorigin/b.css">`),
      files: { "b.css": css(ff(2, "../../../fonts/f02.woff2")) } },
    { id: "css-import-chain", desc: "@import chain across origins, 3 levels", expect: [3, 4],
      html: page(use(3, 4), `<style>@import url("${B}/nocors/case-assets/css-import-chain/l1.css");</style>`),
      files: { "l1.css": css(`@import "l2.css";${ff(3, F(3))}`), "l2.css": css(`@import url(l3.css) layer(x);`), "l3.css": css(ff(4, `${A}${F(4)}`)) } },
    { id: "css-grouping", desc: "@font-face inside @media/@supports/@layer/@container", expect: [5, 6, 7, 8],
      html: page(use(5, 6, 7, 8), `<style>@media screen{${ff(5, F(5))}}@supports (display:grid){${ff(6, F(6))}}@layer a{${ff(7, F(7))}}@media (min-width:1px){@supports (color:red){${ff(8, F(8))}}}</style>`) },
    { id: "css-inline-style", desc: "inline <style>", expect: [9],
      html: page(use(9), `<style>${ff(9, F(9))}</style>`) },
    { id: "css-shadow-open", desc: "<style> in an open shadow root", expect: [10],
      html: page(`<div id=h></div><script>h.attachShadow({mode:"open"}).innerHTML='<style>${ff(10, F(10))}</style><p style="font-family:\\'Vec 10\\'">x</p>';</script>` + use(10)) },
    { id: "css-shadow-closed", desc: "<style> in a closed shadow root", expect: [11], hard: true,
      html: page(`<div id=h></div><script>h.attachShadow({mode:"closed"}).innerHTML='<style>${ff(11, F(11))}</style><p style="font-family:\\'Vec 11\\'">x</p>';</script>` + use(11)) },
    { id: "css-dsd-closed", desc: "declarative closed shadow root", expect: [12], hard: true,
      html: page(`<div><template shadowrootmode="closed"><style>${ff(12, F(12))}</style><p style="font-family:'Vec 12'">x</p></template></div>` + use(12)) },
    { id: "css-adopted", desc: "constructed sheet via adoptedStyleSheets (document + shadow)", expect: [13, 14],
      html: page(use(13, 14) + `<div id=h></div><script>const s=new CSSStyleSheet();s.replaceSync(${JSON.stringify(ff(13, F(13)))});document.adoptedStyleSheets=[s];const t=new CSSStyleSheet();t.replaceSync(${JSON.stringify(ff(14, F(14)))});h.attachShadow({mode:"open"}).adoptedStyleSheets=[t];document.adoptedStyleSheets=[s,t];</script>`) },
    { id: "css-insertrule", desc: "rule inserted via CSSOM insertRule (empty <style> text)", expect: [15],
      html: page(use(15) + `<style id=s></style><script>s.sheet.insertRule(${JSON.stringify(ff(15, F(15)))});</script>`) },
    { id: "css-data-uri", desc: "@font-face with base64 data: URI", expect: [16],
      html: page(use(16), `<style>${ff(16, `data:font/woff2;base64,${b64(16)}`)}</style>`) },
    { id: "css-blob-sheet", desc: "stylesheet from blob: URL", expect: [17],
      html: page(use(17) + `<script>const l=document.createElement("link");l.rel="stylesheet";l.href=URL.createObjectURL(new Blob([${JSON.stringify(ff(17, A + F(17)))}],{type:"text/css"}));document.head.append(l);</script>`) },
    { id: "css-blob-font", desc: "@font-face src is a blob: URL (fetched bytes)", expect: [18],
      html: page(use(18) + `<script>fetch("${F(18)}").then(r=>r.blob()).then(b=>{const s=document.createElement("style");s.textContent='@font-face{font-family:"Vec 18";src:url('+URL.createObjectURL(b)+')}';document.head.append(s);});</script>`) },
    { id: "css-blob-font-revoked", desc: "blob: font URL revoked after load, bytes came from an extension-less XOR-free URL", expect: [19],
      html: page(use(19) + `<script>fetch("/x/f19").then(r=>r.blob()).then(async b=>{const u=URL.createObjectURL(b);const s=document.createElement("style");s.textContent='@font-face{font-family:"Vec 19";src:url('+u+')}';document.head.append(s);await document.fonts.load("16px 'Vec 19'");URL.revokeObjectURL(u);});</script>`) },
    { id: "css-media-print", desc: "@font-face in a print-only / disabled-alternate stylesheet", expect: [20, 21],
      files: { "p.css": css(ff(20, F(20))), "alt.css": css(ff(21, F(21))) },
      html: page(use(20, 21), `<link rel=stylesheet media=print href="p.css"><link rel="alternate stylesheet" title=alt href="alt.css">`) },
    { id: "css-svg-style", desc: "<style> inside inline <svg>", expect: [22],
      html: page(use(22) + `<svg width=10 height=10><style>${ff(22, F(22))}</style></svg>`) },
    { id: "css-weird-url", desc: "font URL with apostrophe, space and parentheses", expect: [23], rename: { "/fonts/it's (f23).woff2": 23 },
      html: page(use(23), `<style>@font-face{font-family:"Vec 23";src:url("/fonts/it's%20(f23).woff2")}</style>`) },
    { id: "css-removed-sheet", desc: "stylesheet removed from DOM after the font loaded", expect: [24],
      files: { "r.css": css(ff(24, F(24))) },
      html: page(use(24), `<link id=l rel=stylesheet href="r.css"><script>addEventListener("load",()=>document.fonts.ready.then(()=>l.remove()));</script>`) },

    { id: "js-fontface-url", desc: "new FontFace(url), loaded", expect: [25],
      html: page(use(25) + `<script>${jsFace(25, `"url(${F(25)})"`)}</script>`) },
    { id: "js-fontface-unloaded", desc: "new FontFace(url), never loaded", expect: [26],
      html: page(`<p>nothing uses it</p><script>${jsFace(26, `"url(${F(26)})"`, false)}</script>`) },
    { id: "js-fontface-buffer-fetch", desc: "fetch() → ArrayBuffer → FontFace", expect: [27],
      html: page(use(27) + `<script>${jsFace(27, `await (await fetch("${F(27)}")).arrayBuffer()`)}</script>`) },
    { id: "js-fontface-xhr-extless", desc: "XHR of extension-less URL → FontFace", expect: [28],
      html: page(use(28) + `<script>const x=new XMLHttpRequest();x.open("GET","/x/f28");x.responseType="arraybuffer";x.onload=()=>{${jsFace(28, "x.response")}};x.send();</script>`) },
    { id: "js-fontface-xor", desc: "obfuscated (XOR) download decoded in JS → FontFace(buffer)", expect: [29], hard: true,
      html: page(use(29) + `<script>${jsFace(29, `new Uint8Array(await (await fetch("/xor/f29")).arrayBuffer()).map(b=>b^90)`)}</script>`) },
    { id: "js-fontface-inline-base64", desc: "base64 font in an inline script → FontFace(buffer)", expect: [30],
      html: page(use(30) + `<script>${jsFace(30, `Uint8Array.from(atob("${b64(30)}"),c=>c.charCodeAt(0))`)}</script>`) },
    { id: "js-fontface-inline-datauri", desc: "FontFace('url(data:…)') in an inline script", expect: [31],
      html: page(use(31) + `<script>${jsFace(31, `"url(data:font/woff2;base64,${b64(31)})"`)}</script>`) },
    { id: "js-bundle-url", anon: true, desc: "font URLs only inside an external JS bundle (type tester list), none loaded", expect: [32, 33],
      files: { "bundle.js": js(`window.STYLES=[{name:"A",file:"/fonts/f32.woff2"},{name:"B",file:"${A}/fonts/f33.woff2"}];`) },
      html: page(`<p>tester</p>`, `<script src="bundle.js"></script>`) },
    { id: "json-manifest", anon: true, desc: "font URLs only in a fetched JSON manifest, none loaded", expect: [34, 35],
      files: { "fonts.json": json({ styles: [{ url: "/fonts/f34.woff2" }, { url: "fonts/f35.woff2" }] }) },
      html: page(`<p>tester</p><script>fetch("fonts.json").then(r=>r.json()).then(j=>window.M=j);</script>`) },
    { id: "js-bundle-base64", desc: "base64 font embedded in an external JS bundle → FontFace(buffer)", expect: [36],
      files: { "embed.js": js(`const F36="${b64(36)}";${jsFace(36, `Uint8Array.from(atob(F36),c=>c.charCodeAt(0))`)}`) },
      html: page(use(36), `<script src="embed.js"></script>`) },
    { id: "js-bundle-datauri-css", desc: "CSS with data: font injected by an external bundle (CSS-in-JS), style later removed", expect: [37],
      files: { "cij.js": js(`const s=document.createElement("style");s.textContent=${JSON.stringify(ff(37, `data:font/woff2;base64,${b64(37)}`))};document.head.append(s);document.fonts.load("16px 'Vec 37'").then(()=>s.remove());`) },
      html: page(use(37), `<script src="cij.js"></script>`) },

    { id: "preload-extless", anon: true, desc: "<link rel=preload as=font> of an extension-less URL, unused", expect: [38],
      html: page(`<p>preload</p>`, `<link rel=preload as=font crossorigin href="/x/f38">`) },
    { id: "prefetch", anon: true, desc: "<link rel=prefetch> of a font", expect: [39],
      html: page(`<p>prefetch</p>`, `<link rel=prefetch href="${F(39)}">`) },
    { id: "http-link-header", anon: true, desc: "HTTP Link: preload header only", expect: [40], headers: { Link: `</x/f40>; rel=preload; as=font; crossorigin` },
      html: page(`<p>header</p>`) },
    { id: "template-style", desc: "@font-face inside an uninstantiated <template>", expect: [41],
      html: page(`<template><style>${ff(41, "/x/f41")}</style></template>`) },
    { id: "noscript-style", desc: "@font-face in <noscript>", expect: [42],
      html: page(`<noscript><style>${ff(42, "/x/f42")}</style></noscript>`) },

    { id: "iframe-same", desc: "same-origin iframe", expect: [43],
      files: { "inner.html": { type: "text/html", body: page(use(43), `<style>${ff(43, F(43))}</style>`) } },
      html: page(`<iframe src="inner.html"></iframe>`) },
    { id: "iframe-srcdoc", desc: "srcdoc iframe with a JS FontFace", expect: [44],
      html: page(`<iframe srcdoc="${page(use(44) + `<script>${jsFace(44, `'url(${F(44)})'`)}</script>`).replace(/&/g, "&amp;").replace(/"/g, "&quot;")}"></iframe>`) },
    { id: "object-embed", desc: "same-origin HTML in <object>", expect: [45],
      files: { "obj.html": { type: "text/html", body: page(use(45), `<style>${ff(45, F(45))}</style>`) } },
      html: page(`<object data="obj.html" type="text/html" width=300 height=100></object>`) },
    { id: "iframe-xorigin", desc: "cross-origin iframe", expect: [46], hard: true,
      html: page(`<iframe src="${B}/case-assets/iframe-xorigin/x.html"></iframe>`),
      files: { "x.html": { type: "text/html", body: page(use(46), `<style>${ff(46, F(46))}</style>`) } } },

    { id: "rt-overflow", desc: "300 resources fill the resource-timing buffer before a JS FontFace loads", expect: [47],
      html: page(`<div id=d></div><script>(async()=>{await Promise.all(Array.from({length:300},(_,i)=>fetch("/px?"+i)));${jsFace(47, `"url(/x/f47)"`).slice(0, -1)}})();</script>` + use(47)) },
    { id: "rt-cleared", desc: "performance.clearResourceTimings() after a JS font loaded", expect: [48],
      html: page(use(48) + `<script>(async()=>{const f=new FontFace("Vec 48","url(/x/f48)");document.fonts.add(f);await f.load();performance.clearResourceTimings();})();</script>`) },
    { id: "worker-fetch", desc: "worker fetches the font, main thread builds FontFace from the buffer", expect: [49],
      files: { "w.js": js(`fetch("/x/f49").then(r=>r.arrayBuffer()).then(b=>postMessage(b,[b]));`) },
      html: page(use(49) + `<script>new Worker("w.js").onmessage=e=>{${jsFace(49, "e.data")}};</script>`) },
    { id: "worker-fontface", desc: "FontFace used only inside a worker (OffscreenCanvas)", expect: [50],
      files: { "w2.js": js(`const f=new FontFace("Vec 50","url(/x/f50)");self.fonts.add(f);f.load();`) },
      html: page(`<p>worker</p><script>new Worker("w2.js");</script>`) },
    { id: "canvas-only", anon: true, desc: "font fetched for a WebGL/canvas text lib, never registered", expect: [51],
      html: page(`<canvas></canvas><script>fetch("/x/f51").then(r=>r.arrayBuffer()).then(b=>window.glyphs=b.byteLength);</script>`) },
    { id: "localstorage-css", desc: "font cached in localStorage as base64 (decoded from an XOR download), FontFace(buffer)", expect: [52],
      html: page(use(52) + `<script>(async()=>{const b=new Uint8Array(await (await fetch("/xor/f52")).arrayBuffer()).map(x=>x^90);let s="";b.forEach(x=>s+=String.fromCharCode(x));localStorage.setItem("font-cache",btoa(s));${jsFace(52, `Uint8Array.from(atob(localStorage.getItem("font-cache")),c=>c.charCodeAt(0))`).slice(0, -1)}})();</script>`) },
    { id: "cachestorage", desc: "font stored in CacheStorage, registered from cache.match()", expect: [53],
      html: page(use(53) + `<script>(async()=>{const c=await caches.open("f");await c.put("/virtual/font",new Response(await (await fetch("/xor/f53")).arrayBuffer().then(b=>new Uint8Array(b).map(x=>x^90))));${jsFace(53, `await (await c.match("/virtual/font")).arrayBuffer()`).slice(0, -1)}})();</script>`) },
    { id: "indexeddb", desc: "font stored in IndexedDB (decoded from XOR), registered from there", expect: [54], hard: true,
      html: page(use(54) + `<script>const q=indexedDB.open("fdb",1);q.onupgradeneeded=()=>q.result.createObjectStore("s");q.onsuccess=async()=>{const buf=new Uint8Array(await (await fetch("/xor/f54")).arrayBuffer()).map(x=>x^90);q.result.transaction("s","readwrite").objectStore("s").put(buf,"font");${jsFace(54, "buf")}};</script>`) },
    { id: "once-url", desc: "signed one-time URL (second request → 403)", expect: [55],
      html: page(use(55), `<style>${ff(55, "/once/f55.woff2?sig=abc")}</style>`) },
    { id: "lazy-interaction", desc: "stylesheet injected only on user interaction", expect: [56],
      files: { "lazy.js": js(`addEventListener("click",()=>{const s=document.createElement("style");s.textContent='@font-face{font-family:"Vec 56";src:url(/fonts/f56.woff2)}';document.head.append(s);},{once:true});`) },
      html: page(`<button>load</button>`, `<script src="lazy.js"></script>`) },
    { id: "ttf-otf-woff", desc: "legacy formats (TTF, WOFF) via CSS", expect: [57, 58],
      html: page(use(57, 58), `<style>${ff(57, F(57, "ttf"))}${ff(58, F(58, "woff"))}</style>`) },
    { id: "nocors-font", desc: "cross-origin font served without CORS (browser rejects it, file still downloadable?)", expect: [59],
      html: page(use(59), `<style>${ff(59, `${B}/nocors/fonts/f59.woff2`)}</style>`) },
    { id: "css-referenced-in-js", desc: "stylesheet URL only in a script (lazy-loaded tester CSS), never loaded", expect: [62],
      files: { "tester.js": js(`window.loadTester=()=>{const l=document.createElement("link");l.rel="stylesheet";l.href="/case-assets/css-referenced-in-js/tester.css";document.head.append(l);};`), "tester.css": css(ff(62, "/x/f62")) },
      html: page(`<p>tester</p>`, `<script src="tester.js"></script>`) },
    { id: "css-link-in-template", desc: "<link rel=stylesheet> inside an uninstantiated <template>", expect: [63],
      files: { "tpl.css": css(ff(63, "/x/f63")) },
      html: page(`<template><link rel=stylesheet href="tpl.css"><p>x</p></template>`) },
    { id: "iframe-lazy", desc: "same-origin iframe with loading=lazy, far below the fold (not loaded yet)", expect: [64],
      files: { "lazy.html": { type: "text/html", body: page(use(64), `<style>${ff(64, "/x/f64")}</style>`) } },
      html: page(`<div style="height:6000px"></div><iframe loading=lazy src="lazy.html"></iframe>`) },
    { id: "js-concat-url", desc: "FontFace URL concatenated from a font-folder constant and a file name", expect: [65], anon: true,
      html: page(`<p>concat</p><script>const FONT_DIR="/fonts/";const files=["f65.woff2"];window.go=()=>new FontFace("Vec 65","url("+FONT_DIR+files[0]+")");</script>`) },
    { id: "iframe-in-shadow", desc: "same-origin iframe inside a web component's shadow root", expect: [66],
      files: { "shadow-inner.html": { type: "text/html", body: page(use(66), `<style>${ff(66, "/x/f66")}</style>`) } },
      html: page(`<div id=h></div><script>h.attachShadow({mode:"open"}).innerHTML='<iframe src="shadow-inner.html"></iframe>';</script>`) },
    { id: "svg-embedded", desc: "SVG image (<img>) with an embedded base64 @font-face", expect: [67], anon: true,
      files: { "logo.svg": { type: "image/svg+xml", body: `<svg xmlns="http://www.w3.org/2000/svg" width="200" height="40"><style>@font-face{font-family:"Vec 67";src:url(data:font/woff2;base64,${b64(67)})}</style><text y="30" font-family="Vec 67">Logo</text></svg>` } },
      html: page(`<img src="logo.svg">`) },
    { id: "sw-precache", desc: "font URL only in the service worker's precache manifest", expect: [68], anon: true,
      files: { "sw.js": js(`self.__WB_MANIFEST=[{url:"/fonts/f68.woff2",revision:"1"}];self.addEventListener("fetch",()=>{});`) },
      html: page(`<p>pwa</p><script>navigator.serviceWorker.register("sw.js");</script>`) },
    { id: "next-other-route-css", desc: "CSS of another route, named only as a relative path in a build manifest", expect: [69], anon: true,
      files: { "_next/static/css/a.css": css("body{margin:0}"), "_next/static/css/b.css": css(ff(69, "/x/f69")), "_next/static/build/_buildManifest.js": js(`self.__BUILD_MANIFEST={"/other":["static/css/b.css","static/chunks/x.js"]};`) },
      html: page(`<p>next</p>`, `<link rel=stylesheet href="/case-assets/next-other-route-css/_next/static/css/a.css"><script src="/case-assets/next-other-route-css/_next/static/build/_buildManifest.js"></script>`) },
    { id: "capture-rerun", desc: "decrypted FontFace(buffer) + revoked blob: CSS font created after the first run (type-tester style switch); second run", expect: [70, 71], second: "#switch",
      html: page(use(70, 71) + `<button id=switch>switch style</button><script>switch_.onclick=async()=>{${jsFace(70, `new Uint8Array(await (await fetch("/xor/f70")).arrayBuffer()).map(b=>b^90)`).slice(0, -1)};const b=new Blob([new Uint8Array(await (await fetch("/xor/f71")).arrayBuffer()).map(x=>x^90)]);const u=URL.createObjectURL(b);const s=document.createElement("style");s.textContent='@font-face{font-family:"Vec 71";src:url('+u+')}';document.head.append(s);await document.fonts.load("16px 'Vec 71'");URL.revokeObjectURL(u);};</script>`.replace("switch_", "document.getElementById('switch')")) },
    { id: "worker-buffer", desc: "font decrypted inside a worker and used there only (OffscreenCanvas), relative URLs", expect: [72], anon: true,
      files: { "wb.js": js(`(async()=>{const b=new Uint8Array(await (await fetch("../xor/f72")).arrayBuffer()).map(x=>x^90);const f=new FontFace("Vec 72",b);self.fonts.add(f);await f.load();})();`) },
      html: page(`<p>worker canvas</p><script>new Worker("wb.js");</script>`) },
    { id: "worker-module-buffer", desc: "module worker decrypts a font and uses it there only", expect: [74], anon: true,
      files: { "wm.js": js(`const b=new Uint8Array(await (await fetch("../xor/f74")).arrayBuffer()).map(x=>x^90);const f=new FontFace("Vec 74",b);self.fonts.add(f);await f.load();`) },
      html: page(`<p>module worker</p><script>new Worker("wm.js",{type:"module"});</script>`) },
    { id: "iframe-data-url", desc: "iframe with a data: URL document (opaque origin)", expect: [73],
      html: page(`<iframe src="data:text/html;base64,${Buffer.from(page(use(73), `<style>${ff(73, `${A}/x/f73`)}</style>`)).toString("base64")}"></iframe>`) },
    { id: "rate-limited", desc: "declared but unused faces on a host that answers 429 (no CORS) twice before serving", expect: [60, 61],
      html: page(`<p>unused</p>`, `<style>${ff(60, "/flaky/f60.woff2")}${ff(61, "/flaky/f61.woff2")}</style>`) },
  ];
}
