name: PSMinifier

on:
  push:
    paths:
      - '**.ps1'

jobs:
  minify-powershell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Minify PowerShell scripts
      uses: StartAutomating/PSMinifier@v1.1.3
      with:
        GZip: false
        CommitMessage: "Minified PowerShell scripts."
